name: .NET

on:
  # push:
  #   branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --logger "trx;LogFileName=${GITHUB_WORKSPACE}/test-results.trx"
    
    - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: tests-results
          path: ${GITHUB_WORKSPACE}/test-results.trx
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: tests-results
        name: Unit Tests
        path: '*.trx'
        reporter: dotnet-trx
