name: .NET

on:
  # push:
  #   branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --logger "trx;LogFileName=${GITHUB_WORKSPACE}/test-results.trx"
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: test-results.trx
        name: unit-tests
        path: ${GITHUB_WORKSPACE}
        reporter: dotnet-trx
